### ISSUE TITLE
We lost the hfhf domain editor panel

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle.editor#1]
Oops!
![image](https://user-images.githubusercontent.com/124158/47446270-e73f2780-d788-11e8-918d-465bb9da46fa.png)

Sys link is this: 
![image](https://user-images.githubusercontent.com/124158/47446284-ef976280-d788-11e8-91e5-a1717c8ecbf8.png)

**Comment by khardenstine** [comment]
(tools.database/rollback (d/connect root-uri) 13194139550760)
